FROM ubuntu:latest
RUN apt-get update 
RUN apt-get -qqy install git
# Modifiquem usuari. Abans ho executava ROOT i ara ho executarà un usuari.
USER 1000
# El següent programa l'executarà l'user 1000 (primer usuari del sistema)
RUN EJECUTAR PROGRAMA
## podemos ejecutar lo mismo pero en 2 lineas en lugar de 3
FROM ubuntu:latest
RUN apt-get update && apt-get -qqy install git

## lo mejor es 



